Python 3.14.6 (tags/v3.14.6:c63aec6, Jun 10 2026, 10:26:10) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> try:
...     
...     file = open("user_logs.txt", "a")
... 
...     
...     for i in range(5):
...         action = input("Enter user action: ")
...         file.write(action + "\n")
... 
...     file.close()
... 
...     print("Logs saved successfully.")
... 
... except FileNotFoundError:
...     print("File not found.")
... 
... except PermissionError:
...     print("Permission denied.")
... 
... except Exception as e:
...     print("Error:", e)
... 
...     
Permission denied.
